# GitHub Actions Tutorial: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

name: discord-plex-bot-ci
run-name: Build & Test
on: [push]

jobs:
  install:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Get Node Version
        run: node -v
      - name: Get NPM Version
        run: npm -v
      - name: Run Formatter
        run: npm format:check
      - name: Run Linter
        run: npmlint:check
      - name: Run Unit Tests
        run: npm test
