# GitHub Actions Tutorial: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

name: discord-plex-bot-ci
run-name: Build & Test
on: [push]

jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Step Up & Run Checks
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Get Node Version
        run: node -v
      - name: Get NPM Version
        run: npm -v
      - name: Run Formatter
        run: npm run format:check
      - name: Run Linter
        run: npm run lint:check
      - name: Run Unit Tests
        run: npm test
      - name: Compile TypeScript
        run: npm run build

  deploy:
    runs-on: ubuntu-22.04
    needs: check
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        run: process.exit(0)
