# GitHub Actions Tutorial: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

# https://faun.pub/full-ci-cd-with-docker-github-actions-digitalocean-droplets-container-registry-db2938db8246

# https://docs.digitalocean.com/products/container-registry/how-to/use-registry-docker-kubernetes/

name: discord-plex-bot-ci
run-name: Build & Test
on: [push]

env:
  REGISTRY: 'registry.digitalocean.com/discord-plex-bot-image'
  IMAGE_NAME: 'discord-plex-bot-image'

jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Step Up & Run Checks
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Get Node Version
        run: node -v

      - name: Get NPM Version
        run: npm -v

      - name: Run Formatter
        run: npm run format:check

      - name: Run Linter
        run: npm run lint:check

      - name: Run Unit Tests
        run: npm test

      - name: Compile TypeScript
        run: npm run build

  deploy:
    runs-on: ubuntu-22.04
    needs: check
    # if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Step Up & Run Checks
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
