name: discord-plex-bot-ci
run-name: Build & Test
on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Formatter
        run: npm run format:check

      - name: Run Linter
        run: npm run lint:check

      - name: Run Unit Tests
        run: npm test

      - name: Compile TypeScript
        run: npm run build

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-22.04
  #   needs: build
  #   if: success() && github.ref == 'refs/heads/master'

  #   steps:
  #     - name: Deploy To DigitalOcean
  #       uses: digitalocean/app_action@v1.1.5
  #       with:
  #         app_name: discord-plex-bot-app
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
